#+title: Daily work log for A Namratha Deepthi

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
      Learn git (add, commit,push, pull, clone and fork)
      Learn  emacs 
   + What did I get done against each task?
     Git- worked with local repository and remote repository.
     Got a brief idea about emacs and the various commands used to navigate
     through it.

** [2016-05-17 Tue]
   + Task assigned today:
     Develop a simple web application that maintains list of users and their emails.
      Today's task was to gather the requirements and develop a data model for the user-email-directory.
   + What did I get done against each task?
     Worked with org mode and formulated the requirements and the data-model.  
     Datamodel: The actors in the system and their relationships and interactions were formulated using specific notations.
                The datamodel developed can be found in the repository vlabproject.
** [2016-05-18 Wed]
   + Task assigned today:
     Object Oriented Programming in python and development of the object model.
   + What did I get done against each task?
     We worked in teams and completed the class definitions and wrote appropriate test-cases for the user-email directory.
     
** [2016-05-19 Thurs]
   + Task assigned today:
     Complete the object model including the session class and the documentation.
   + What did I get done against each task?
     We worked on different branches and completed the definitions of session class and wrote unit test cases for the same.
     During the process learnt how to organize test code using setup and teardown mehods.

** [2016-05-20 Fri]
    + Task assigned today:
     Complete the object model - the system class.
    + What did I get done against each task?
     We completed writing the various operations of system class and a few test
     cases.                            
     
** [2016-05-23 Mon]
    + Task assigned today:
      We had to start working on the Object Relational Model.
    + What did I get done against each task?
      In the process we learnt about SQLALCHEMY, flask and the other
      dependencies needed to work with the ORM. The User class and Role class
      were redefined to now include persistance.   
** [2016-05-25 Wed]
    + Task assigned today:
      We had to finish the REST API .
    + What did I get done against each task?
      Learnt about Flask and REST API architecture.We implemented the REST API
      structure for the user-directory .   
** [2016-05-26 Thurs]
    + Task assigned today:
      We had to write the test cases for the  REST API .
    + What did I get done against each task?
      Understood how exactly the System works ( ie. in the REST API all the calls have be done using System object only) .
      We completed the test cases.
** [2016-05-27 Fri]
    + Task assigned today:
      Understand how the front end of the app works.
    + What did I get done against each task?
      Sripathi sir explained the MVC framework of angular js and we understood how to implement the front end for our app.
      
** Weekly  Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   
** [2016-05-30 Mon]
    + Task assigned today:
      To start working on the front end.
    + What did I get done against each task?
      We worked with view user and get users part but got stuck with errors(cache wasnt getting cleared). Couldn't figure them
      out.
      
** [2016-05-31 Tue]
    + Task assigned today:
      Finish front end.
    + What did I get done against each task?
      The errors we faced yesterday were debugged and we implemented add user and edit user today.


* Month of June
** [2016-06-1 Web]
    + Task assigned today:
      Finish front end.
    + What did I get done against each task?
      We fixed the errors like adding session variables in angular js and implemented delete user. We finished front end.
      
** [2016-06-2 Thurs]
    + Task assigned today:
      We had to do manual deployment and automatic deployment of our web application.
    + What did I get done against each task?
      We deplo
      
* Month of July
