#+title: Daily work log for A Namratha Deepthi

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
      Learn git (add, commit,push, pull, clone and fork)
      Learn  emacs 
   + What did I get done against each task?
     Git- worked with local repository and remote repository.
     Got a brief idea about emacs and the various commands used to navigate
     through it.

** [2016-05-17 Tue]
   + Task assigned today:
     Develop a simple web application that maintains list of users and their emails.
      Today's task was to gather the requirements and develop a data model for the user-email-directory.
   + What did I get done against each task?
     Worked with org mode and formulated the requirements and the data-model.  
     Datamodel: The actors in the system and their relationships and interactions were formulated using specific notations.
                The datamodel developed can be found in the repository vlabproject.
** [2016-05-18 Wed]
   + Task assigned today:
     Object Oriented Programming in python and development of the object model.
   + What did I get done against each task?
     We worked in teams and completed the class definitions and wrote appropriate test-cases for the user-email directory.
     
** [2016-05-19 Thurs]
   + Task assigned today:
     Complete the object model including the session class and the documentation.
   + What did I get done against each task?
     We worked on different branches and completed the definitions of session class and wrote unit test cases for the same.
     During the process learnt how to organize test code using setup and teardown mehods.

** [2016-05-20 Fri]
    + Task assigned today:
     Complete the object model - the system class.
    + What did I get done against each task?
     We completed writing the various operations of system class and a few test
     cases.                            
     
** [2016-05-23 Mon]
    + Task assigned today:
      We had to start working on the Object Relational Model.
    + What did I get done against each task?
      In the process we learnt about SQLALCHEMY, flask and the other
      dependencies needed to work with the ORM. The User class and Role class
      were redefined to now include persistance.   
** [2016-05-25 Wed]
    + Task assigned today:
      We had to finish the REST API .
    + What did I get done against each task?
      Learnt about Flask and REST API architecture.We implemented the REST API
      structure for the user-directory .   
** [2016-05-26 Thurs]
    + Task assigned today:
      We had to write the test cases for the  REST API .
    + What did I get done against each task?
      Understood how exactly the System works ( ie. in the REST API all the calls have be done using System object only) .
      We completed the test cases.
** [2016-05-27 Fri]
    + Task assigned today:
      Understand how the front end of the app works.
    + What did I get done against each task?
      Sripathi sir explained the MVC framework of angular js and we understood how to implement the front end for our app.
      
** Weekly  Summary
   + What are the insights gained?
   + What is my footprint in the realization of the project?
   
** [2016-05-30 Mon]
    + Task assigned today:
      To start working on the front end.
    + What did I get done against each task?
      We worked with view user and get users part but got stuck with errors(cache wasnt getting cleared). Couldn't figure them
      out.
      
** [2016-05-31 Tue]
    + Task assigned today:
      Finish front end.
    + What did I get done against each task?
      The errors we faced yesterday were debugged and we implemented add user and edit user today.


* Month of June
** [2016-06-1 Web]
    + Task assigned today:
      Finish front end.
    + What did I get done against each task?
      We fixed the errors like adding session variables in angular js and implemented delete user. We finished front end.
      
** [2016-06-2 Thurs]
    + Task assigned today:
      We had to do manual deployment and automatic deployment of our web application.
    + What did I get done against each task?
      We deployed the web application deployed on an external host, using both a manual deployment and an ADS.

** [2016-06-3 Fri]
    + Task I was assigned today?
      We had to give a small presentation on the completed web application, and present the completed documentation.
    + What did I get done against the task?
      We presented the documentation on the completed web application, and demonstrated the working of the application, along with displaying the running test cases.
      
      
** Weekly  Summary
   + What are the insights gained?
     I learnt to build a web application from scratch ( end to end applicaation), right from requirements determination till deployment ( manual and automated)
  
      
** [2016-06-6 Mon]
   + Task assigned today:
     Today, we had to work on preparing the data model for the already existing outreach portal.
   + What did I get done against each task?
     We prepared the data model for the currently deployed outreach portal.
     
** [2016-06-7 Tue]
   + Today's task:
     Today, we discussed about the old model and started building the Audit module. The Audit module was built for the user directory and this will be used later for the outreach portal. The basic use of Audit module is to keep track who is doing what in the web-app, it makes a record of ll the updations and deletions in the web-app.
** [2016-06-8 Wed]
   + Today's task:
     Write test cases for the Audit class.
   + What did I get done against each task?
     We wrote testcases (  for login, add user, delete user and update user) in the Audit module. 
     
** [2016-06-9 Thurs]
   + Today's task:
     Since Firefox is going to stop providing Persona service in the coming months, we had to figure out how to use Open-Id authentication in our web-app.
   + What did I get done against each task?
     I read through the documentation of Open-Id. Didn't do much today, as I was figuring out what Open-ID actually is.
    
** [2016-06-10 Fri]
   + Today's task:
     Had to try implementing Open-Id.
   + What did I get done against each task?
     I tried to run an example that runs Open-Id, in the process I realized that each user has to first obtain their open-id from the providers like yahoo using their yahoo-id. And getting an open id with gmail, proved to be a tough task.(OpenID allows you to use an existing account to sign in to multiple websites, without needing to create new passwords). If users' obtain their open id, then the requirements of using it in place of persona is feasible butthe problem lies with obtaining a open-id.
     
** [2016-05-16 Thurs]
    + Task assigned today:
      We had to start working on the data-model of the new outreach portal.
    + What did I get done against each task?
      We described the various entities, primary-sets , derived-sets  discussed yesterday, and the CRUD operations in the data-model.
      
* Month of July
